name: Build

on:
  push:
    paths-ignore:
      - "**.md"
      - ".gitattributes"
      - ".gitignore"
      - "CODEOWNERS"
      - "LICENCE"
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: true
      - run: ./gradlew clean build
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-reports
          path: |
            **/build/reports/
            **/build/test-results/
